version: '2.0'

services:
  api:
    container_name: nest_api
    build: .
    ports: ['3000:3000']
    volumes:
      - .:/home/api
      - ./home/api/node_modules

  database:
    container_name: nest_db
    image: mysql
    environment:
      MYSQL_DATABASE: nest_api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql:rw,delegated
